### ISSUE TITLE
Rand::normal does not finish

### ISSUE THREAD

**Issue by bbensaid30** [bab2min/EigenRand#27]
Hello

I just tried the following line of codes:
```
#include <Eigen/Dense>
#include <EigenRand/EigenRand>

Eigen::Rand::Vmt19937_64 gen{ 42 };
Eigen::MatrixXd test = Eigen::Rand::normal<Eigen::MatrixXd>(3,3,gen,0,1);
std::cout << test << std::endl;`
```
I have no compilation issue (just warnings but I think it is normal according to another discussion issue on gitlab). However, I can wait 10 mins and I have absolutely no results.
I compile with g++ (C++ 17 or 11) and I have the Eigen version 3.7.7.

Thanks in advance

**Comment by bab2min** [comment]
Hi @bbensaid30 , thank you for your interest to my package.
Umm, it seems to be an OS or hardware related problem.
Could you share more information about your environment, including your OS and CPU architecture. 
Also you can get verbose g++ log with `-Q --help=target -v` option. (`g++ yourcode.cpp -Q --help=target -v`)
If you share your verbose log and compiled binary, it will be very helpful to solve the problem.

**Comment by bbensaid30** [comment]
Hello
My OS: Ubuntu 20.04.2 (Debian)
The other information are in the following files.
[debug.zip](https://github.com/bab2min/EigenRand/files/6789986/debug.zip)

**Comment by bbensaid30** [comment]
Hello

Do you find the problem please ?

**Comment by bab2min** [comment]
Hello @bbensaid30 
It seems that I've identified the cause of the problem.
It only happens with an odd size of double matrices where vectorization is not possible, such as 3x3 or 5x5 matrix.
If you test with 4x4 matrix, it will run without the problem.

The cause of the problem is that `UniformReal` generator for `double` type yields wrong distribution in scalar mode. I'll fix it as soon as possible. Please wait a little longer.

**Comment by bab2min** [comment]
@bbensaid30 
I've uploaded a new version 0.3.5 that fixes the issue. Please test the same code with the new version.

**Comment by bbensaid30** [comment]
Thanks it works fine. Good work!
