### ISSUE TITLE
"fatal error: 'Eigen/Dense' file not found" when using Eigen in header-only mode

### ISSUE THREAD

**Issue by hxhc** [bab2min/EigenRand#36]
hello Bab2min, I am a novice at C++ and Eigen. I found your EigenRand library yesterday and I think it is awesome. However, I came across 2 issues.

1. I use eigen with header-only mode, and I put the Eigen library under `./libs`. Since EigenRand is also header only, I put EigenRand under `./libs`, too. The file structure is shown in the picture.
![image](https://user-images.githubusercontent.com/13412966/159201003-25821be4-bf49-434d-b147-0e075b024d5f.png)

Then I use the code below to test EigenRand, and compile the eigen_demo.cpp with
 `clang++ eigen_demo.cpp -I libs/Eigen/ -I libs/EigenRand/  -o ./output/eigen_demo -lmkl_intel_lp64 -lmkl_gnu_thread -lmkl_core -lgomp -lpthread -lm -ldl -I /usr/include/mkl`

However, it raised an error. I am not sure how to solve it. Is there something wrong in the compile command?

> "In file included from eigen_demo.cpp:10:
> ./libs/EigenRand/EigenRand:15:10: fatal error: 'Eigen/Dense' file not found
> #include <Eigen/Dense>
         ^~~~~~~~~~~~~
> 1 error generated."

```cpp
#define EIGEN_USE_BLAS
#define EIGEN_USE_LAPACK
#define EIGEN_USE_MKL_ALL

#include <iostream>
#include <chrono>
#include <ctime>
#include <random>
#include "libs/Eigen/Dense"
#include "libs/EigenRand/EigenRand"

void RunTest(int size=100, size_t loops=10)
{
    for (size_t i = 0; i <= loops; ++i)
    {
        std::srand((unsigned)time(NULL));
        int urng  = std::rand();
        Eigen::Rand::NormalGen<double> norm_gen{ 0.0, 1.0 };
        Eigen::MatrixXd A = norm_gen.template generate<Eigen::MatrixXd>(size, size, urng);
        Eigen::MatrixXd B = A * A;
        std::cout << urng << std::endl;
    }
}

int main(){
    RunTest();
    return 0;
}
```

2. The other issue is that if I want to change the random seed in every loop, what is the proper way to achieve the goal. I use the `srand` function, but I did't try because the code can't be compiled.😂

Because I am quite new to C++, I have to ask you for solutions. Hope I claimed the questions clearly and thank you for your great work.

**Comment by bab2min** [comment]
Hi @hxhc ,
First, since the compiler finds a header file named `some_header` in the **include path** at the preprocess directive `#include <some_header>`, you should set your include path to `libs` not `libs/Eigen` nor `libs/EigenRand` as follows:
`clang++ eigen_demo.cpp -I libs -o ./output/eigen_demo -lmkl_intel_lp64 -lmkl_gnu_thread -lmkl_core -lgomp -lpthread -lm -ldl -I /usr/include/mkl`
And, the include path will be corrected like:
```c++
#include <Eigen/Dense>
#include <EigenRand/EigenRand>
```

Second, it is recommended to use c++ standard random library not `rand()`.  You can see the detailed examples at https://bab2min.github.io/eigenrand/v0.4.0alpha/en/getting_started.html .

**Comment by hxhc** [comment]
Thank you so much! My problems are perfectly solved. Sorry for my stupid issue.😂
